// Full Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)
// *** Do NOT edit this file! If you need to add something, add it in "mission\scripts.sqf" - It'll still run here! ***
waitUntil { isServer || !isNull player };
bravo_f3_mod_var_missionVersion = "MOD1.0";

bravo_f3_mod_var_AuthorUID = '76561198041097857';
// ====================================================================================
// MISSION SPECIFIC SCRIPTS AND VARIABLES
#if __has_include("\bravo_f3_mod\includes\missionscripts.sqf")
	#include "\bravo_f3_mod\includes\missionscripts.sqf"
#endif
#include "scripts.sqf";
// ====================================================================================